os:
  - linux
  - osx
sudo: false
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  matrix:
    - TRAVIS_NODE_VERSION="0.10"
    - TRAVIS_NODE_VERSION="0.12"
    - TRAVIS_NODE_VERSION="2"
    - TRAVIS_NODE_VERSION="4.1"
    - TRAVIS_NODE_VERSION="5.1"
    - TRAVIS_NODE_VERSION="5" JPM="1"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  # Install dependencies and build
  - npm install

script:
  # Output useful info for debugging
  - node --version
  - npm --version
  - which firefox
  # Run tests
  - if [[ $JPM == "1" ]]; then jpm test; else npm test; fi
